### ISSUE TITLE
Problem with W7

### ISSUE THREAD

**Issue by ZindelPama** [dboglobal/DBOGLOBAL#3]
When you close the map gui the client crash.
This problem only happens on w7, with 8.1 and 10 it works fine.

**Comment by daparache** [comment]
hola bro dime una cosa

**Comment by daparache** [comment]
tu cliente esta funcionando y todo ?

**Comment by ZindelPama** [comment]
yep

**Comment by dboguser** [comment]
Fixed
https://github.com/dboglobal/DBOGLOBAL/commit/cf9ef59494d27f0b848b5dddc251ff190031e91d
