### ISSUE TITLE
Error compiling client

### ISSUE THREAD

**Issue by ghost** [dboglobal/DBOGLOBAL#4]
After the v140 update client is not compiling as expected.
Both Lib and Shared compile successfully  but client is throwing the following error:
`1>libjpeg.lib(jerror.obj) : error LNK2001`
I did get the GFX located in the right folder.

**Comment by ghost** [comment]
I manage to fix another error in `DboClient/Lib/NtlGui/gui_componenttokenizer.cpp`
Change:
```c++
WriteError(L"Missing '"L"' following '"L"'-begin");
```
To:
```c++
WriteError(L"Missing '" L"' following '" L"'-begin");
```

With C++11 user-defined literal it tries to use the second and third L as a UDF.

Tried to create a PR but I am not authorized

**Comment by eciervo** [comment]
In order to create a pull request you can also fork and work on your fork. Then you can create a pull request to the main (this) repo.

With v120 I didn't have any issue, but I think that should be tested for newer one. Anyway, the code is not ready yet for C++11, I think

**Comment by ghost** [comment]
Thanks, I manage to solve this problem changing a folder name.
`\DboClient\Lib\NtlFlasher\GFx SDK 3.3\3rdParty\jpeg-6b\lib\Win32\Msvc142\Release`
Changed `Msvc80` to `Msvc142`
You can verify this going into project properties -> Linker -> General -> Additional Library Directories

**Comment by dboguser** [comment]
The issue is fixed in the repo.
