### ISSUE TITLE
client cant run.

### ISSUE THREAD

**Issue by odasm** [dboglobal/DBOGLOBAL#5]
when i run the client ..it tips:

CNtlPLEmblemStuffList::LoadScript (75) : [ASSERT] Can not load scprit file of name : .\script\emblemstuff.dat  how to fixed

**Comment by dboguser** [comment]
Hi,

have you made any modifications?
Check if you have the emblemstuff.dat file inside your script folder

**Comment by odasm** [comment]
have the files...i dont modify the file.

**Comment by dboguser** [comment]
Did you download our game client at https://forum.dboglobal.to ?

**Comment by odasm** [comment]
yes...file size:3.06G

**Comment by dboguser** [comment]
Please download this one https://www.transfernow.net/T3nJ9U042020

**Comment by odasm** [comment]
thanks,i'll try it .

**Comment by odasm** [comment]
> Please download this one https://www.transfernow.net/T3nJ9U042020

bro,could you upload the client to mega? thats site speed so low..

**Comment by dboguser** [comment]
https://mega.nz/file/DU8FXIrA#YyOpkQ4932ZCwnWxb4izPO58UguCwn3O3gA70lrP52Q

**Comment by odasm** [comment]
thanks a lot....bro
